const privacyPolicy = {
    'Ⅰ.  What are our disclosure policy?': `
    World Food Cuisine is a personal blog written and edited by Vaishali Jeenwal. 
    This blog accepts forms of cash advertising, sponsorship, paid insertions or other forms of compensation.   
    The compensation received will never influence the content, topics or posts made in this blog. 
    All advertising is in the form of advertisements generated by a third party ad network. 
    Those advertisements will be identified as paid advertisements. From time to time, we do receive compensation for creating recipes and reviewing products; 
    however, compensation will never influence the opinions we share. This blog does not contain any content which might present a conflict of interest.`,
    'Ⅱ.  Read Our latest privacy policy': `
    Effective as of May 1, 2022

    As the owner of this website (the “Site”), Spend With Pennies (“we” or “us”) understand that your privacy is of critical importance.  
    This Privacy Policy describes what information we collect from you via the Site and how we use and disclose such information.`,
    'Ⅲ.  Why and how we are collecting cookies?':`
    A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. 
    The identifier is then sent back to the server each time the browser requests a page from the server. 
    Cookies may be either “persistent” cookies or “session” cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, 
    unless deleted by the user before the expiry date; a session cookie, on the other hand, 
    will expire at the end of the user session, when the web browser is closed.  
    Cookies do not typically contain any information that personally identifies a user, 
    but personal information that we store about you may be linked to the information stored in and obtained from cookies.

    We use cookies for the following purposes:
    
    (a) authentication – we use cookies to identify you when you visit our website and as you navigate our website;
    
    (b) status – we use cookies to help us to determine if you are logged into our website;
    
    (c) personalization – we use cookies to store information about your preferences and to personalize the website for you;
    
    (d) security – we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally;
    
    (e) advertising – we use cookies to help us to display advertisements that will be relevant to you; and
    
    (f) analysis – we use cookies to help us to analyze the use and performance of our website and services;
        `,
    'Ⅳ. What are our advertising policy?':`
    How Your Information Maybe Used

    We may use the information collected in the following ways:
    
    To operate and maintain the Website;
    To send you promotional information, such as newsletters. Each email promotion will provide information on how to opt-out of future mailings;
    To send you administrative communications, such as administrative emails, confirmation emails, technical notices, updates on policies, or security alerts;
    To respond to your comments or inquiries;
    To provide you with user support;
    To track and measure advertising on the Website;
    To protect, investigate, and deter against unauthorized or illegal activity.
    Third Party
    
    We may share your information with third parties when you explicitly authorize us to share your information.    `,
    'Ⅴ. Be free to contact us?':`
    If you have any questions about this Privacy Policy, or the practices of this Site, please contact us at worldfoodcuisine@gmail.com.  
    If you believe that any information we are holding on you is incorrect or incomplete, please contact us.    `,
  
  };

  export default privacyPolicy;